// CHECKSTYLE:OFF
/**
 * Source code generated by Fluent Builders Generator
 * Do not modify this file
 * See generator home page at: http://code.google.com/p/fluent-builders-generator-eclipse-plugin/
 */

package org.magnum.soda.protocol.generic;

import org.magnum.soda.marshalling.Marshaller;

public class UnmarshallingInvocationRespMsgBuilder
		extends
		UnmarshallingInvocationRespMsgBuilderBase<UnmarshallingInvocationRespMsgBuilder> {
	public static UnmarshallingInvocationRespMsgBuilder unmarshallingInvocationRespMsg() {
		return new UnmarshallingInvocationRespMsgBuilder();
	}

	public UnmarshallingInvocationRespMsgBuilder() {
		super(new UnmarshallingInvocationRespMsg());
	}

	public UnmarshallingInvocationRespMsg build() {
		return getInstance();
	}
}

class UnmarshallingInvocationRespMsgBuilderBase<GeneratorT extends UnmarshallingInvocationRespMsgBuilderBase<GeneratorT>> {
	private UnmarshallingInvocationRespMsg instance;

	protected UnmarshallingInvocationRespMsgBuilderBase(
			UnmarshallingInvocationRespMsg aInstance) {
		instance = aInstance;
	}

	protected UnmarshallingInvocationRespMsg getInstance() {
		return instance;
	}

	@SuppressWarnings("unchecked")
	public GeneratorT withMarshaller(Marshaller aValue) {
		instance.setMarshaller(aValue);

		return (GeneratorT) this;
	}

	@SuppressWarnings("unchecked")
	public GeneratorT withResultType(Class<?> aValue) {
		instance.setResultType(aValue);

		return (GeneratorT) this;
	}

	@SuppressWarnings("unchecked")
	public GeneratorT withResult(Object aValue) {
		instance.setResult(aValue);

		return (GeneratorT) this;
	}

	@SuppressWarnings("unchecked")
	public GeneratorT withException(Exception aValue) {
		instance.setException(aValue);

		return (GeneratorT) this;
	}

	@SuppressWarnings("unchecked")
	public GeneratorT withId(String aValue) {
		instance.setId(aValue);

		return (GeneratorT) this;
	}

	@SuppressWarnings("unchecked")
	public GeneratorT withResponseTo(String aValue) {
		instance.setResponseTo(aValue);

		return (GeneratorT) this;
	}

	@SuppressWarnings("unchecked")
	public GeneratorT withSource(String aValue) {
		instance.setSource(aValue);

		return (GeneratorT) this;
	}

	@SuppressWarnings("unchecked")
	public GeneratorT withDestination(String aValue) {
		instance.setDestination(aValue);

		return (GeneratorT) this;
	}
}
