// CHECKSTYLE:OFF
/**
 * Source code generated by Fluent Builders Generator
 * Do not modify this file
 * See generator home page at: http://code.google.com/p/fluent-builders-generator-eclipse-plugin/
 */

package org.magnum.soda.svc;

public class InvocationInfoBuilder extends
		InvocationInfoBuilderBase<InvocationInfoBuilder> {
	public static InvocationInfoBuilder invocationInfo() {
		return new InvocationInfoBuilder();
	}

	public InvocationInfoBuilder() {
		super(new InvocationInfo());
	}

	public InvocationInfo build() {
		return getInstance();
	}
}

class InvocationInfoBuilderBase<GeneratorT extends InvocationInfoBuilderBase<GeneratorT>> {
	private InvocationInfo instance;

	protected InvocationInfoBuilderBase(InvocationInfo aInstance) {
		instance = aInstance;
	}

	protected InvocationInfo getInstance() {
		return instance;
	}

	@SuppressWarnings("unchecked")
	public GeneratorT withMethod(String aValue) {
		instance.setMethod(aValue);

		return (GeneratorT) this;
	}

	@SuppressWarnings("unchecked")
	public GeneratorT withParameters(Object[] aValue) {
		instance.setParameters(aValue);

		return (GeneratorT) this;
	}

	@SuppressWarnings("unchecked")
	public GeneratorT withParameterTypes(Class<?>[] aValue) {
		instance.setParameterTypes(aValue);

		return (GeneratorT) this;
	}
}
